# Generated by Django 5.1.5 on 2025-05-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingorganizer',
            unique_together={('meeting', 'student')},
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['date', 'club'], name='meet_date_club_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['date', 'room'], name='meet_date_room_idx'),
        ),
    ]
